version: '3'
services:
  sdnext:
    image: saladtechnologies/a1111:dynamic
    build:
      context: .
      dockerfile: Dockerfile
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              capabilities: [ gpu ]
              count: all
    ports:
      - 7860:7860
    volumes:
      - ./models:/data/models
      - ./controlnet-models:/data/config/auto/extensions/sd-webui-controlnet/models
    environment:
      # A comma separated list of model version ids to load
      CIVITAI_MODEL_VERSION_IDS: 135867,126688

      # Set to 1 to enable the refiner
      # LOAD_REFINER: 0

      # Set to 1 to enable base sdxl
      LOAD_SDXL_BASE: 1

      # Comma separated list of download urls for controlnets
      CONTROLNET_URLS: https://huggingface.co/lllyasviel/sd_control_collection/resolve/main/diffusers_xl_canny_mid.safetensors?download=true
