#! /usr/bin/env bash

## Usage: ./build [--push]
set -euo pipefail

if [[ $# -gt 0 && $1 == "--push" ]]; then
  push=true
else
  push=false
fi

git_sha=$(git rev-parse --short HEAD)

docker buildx build \
  -t saladtechnologies/a1111:dynamic \
  -f Dockerfile \
  --platform linux/amd64 \
  --output type=docker \
  --provenance false \
  .

docker tag saladtechnologies/a1111:dynamic saladtechnologies/a1111:dynamic-$git_sha

if [ "$push" = true ]; then
  echo "Pushing saladtechnologies/a1111:dynamic"
  docker push saladtechnologies/a1111:dynamic

  echo "Pushing saladtechnologies/a1111:dynamic-$git_sha"
  docker push saladtechnologies/a1111:dynamic-$git_sha
fi
